// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: wrapper.proto

package wrapper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EC2Service_CreateInstance_FullMethodName = "/wrapper.EC2Service/CreateInstance"
)

// EC2ServiceClient is the client API for EC2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EC2ServiceClient interface {
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
}

type eC2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEC2ServiceClient(cc grpc.ClientConnInterface) EC2ServiceClient {
	return &eC2ServiceClient{cc}
}

func (c *eC2ServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, EC2Service_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EC2ServiceServer is the server API for EC2Service service.
// All implementations must embed UnimplementedEC2ServiceServer
// for forward compatibility.
type EC2ServiceServer interface {
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	mustEmbedUnimplementedEC2ServiceServer()
}

// UnimplementedEC2ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEC2ServiceServer struct{}

func (UnimplementedEC2ServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedEC2ServiceServer) mustEmbedUnimplementedEC2ServiceServer() {}
func (UnimplementedEC2ServiceServer) testEmbeddedByValue()                    {}

// UnsafeEC2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EC2ServiceServer will
// result in compilation errors.
type UnsafeEC2ServiceServer interface {
	mustEmbedUnimplementedEC2ServiceServer()
}

func RegisterEC2ServiceServer(s grpc.ServiceRegistrar, srv EC2ServiceServer) {
	// If the following call pancis, it indicates UnimplementedEC2ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EC2Service_ServiceDesc, srv)
}

func _EC2Service_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EC2ServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EC2Service_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EC2ServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EC2Service_ServiceDesc is the grpc.ServiceDesc for EC2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EC2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wrapper.EC2Service",
	HandlerType: (*EC2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstance",
			Handler:    _EC2Service_CreateInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wrapper.proto",
}
